#!/bin/bash

dir=$(dirname $0)
changed="$(find $dir/rsp -newer $dir/rsp/rsp)"
if [[ -n "$changed" ]]; then
  echo Rebuilding...
  cd $dir/rsp
  go build
  cd ..
  echo Regenerating tags...
  ctags -R .
  echo Launching...
fi

./rsp/rsp "$@"
