#!/bin/bash

dir=$(dirname $0)
changed="$(find $dir/rsp -newer $dir/rsp/rsp)"
if [[ -n "$changed" ]]; then
  echo Rebuilding... > /dev/stderr
  cd $dir/rsp
  go build
  cd ..
  echo Regenerating tags... > /dev/stderr
  ctags -R .
  echo Launching... > /dev/stderr
fi

./rsp/rsp "$@"
