-- Support 3d space
CREATE EXTENSION IF NOT EXISTS cube;

CREATE TABLE IF NOT EXISTS stars (
  designation TEXT PRIMARY KEY,
  name TEXT NULL,
  entry_point TEXT NOT NULL,
  est_planets SMALLINT NOT NULL,
  spectral_type TEXT NOT NULL,
  explored BOOLEAN,
  has_life BOOLEAN,
  position CUBE NOT NULL,
  has_hub BOOLEAN,
  has_my_hub BOOLEAN NOT NULL DEFAULT false,
  region TEXT NOT NULL
);

CREATE INDEX idx_stars_position ON stars USING GIST (position);

CREATE TABLE IF NOT EXISTS planets (
  designation TEXT PRIMARY KEY,
  star TEXT NOT NULL,
  name TEXT NULL,
  life_stage TEXT NULL,
  moons SMALLINT NOT NULL,
  rings BOOLEAN,
  scanned BOOLEAN,
  type TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS moons (
  designation TEXT PRIMARY KEY,
  planet TEXT NOT NULL,
  star TEXT NOT NULL,
  name TEXT NULL,
  scanned BOOLEAN,
  type TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS belts (
  designation TEXT PRIMARY KEY,
  star TEXT NOT NULL REFERENCES stars(designation),
  density TEXT NOT NULL,
  mining BOOLEAN,
  resources JSONB
);

CREATE TABLE IF NOT EXISTS aliases (
  designation TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS alias_types (
  type TEXT PRIMARY KEY,
  prefix TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS blueprints (
  type TEXT PRIMARY KEY,
  print_time INTERVAL NOT NULL,
  attach_capacity SMALLINT NOT NULL,
  cargo_capacity SMALLINT NOT NULL,
  stow_capacity SMALLINT NOT NULL,
  short TEXT,
  description TEXT,
  alias TEXT,
  directives TEXT[],
  features TEXT[],
  ingredients JSONB
);

CREATE TABLE IF NOT EXISTS notifications(
  id SERIAL PRIMARY KEY,
  start_ts TIMESTAMPTZ NULL,
  end_ts TIMESTAMPTZ NOT NULL,
  device TEXT NULL,
  text TEXT NOT NULL,
  read BOOLEAN,
  object JSONB
);

CREATE TABLE IF NOT EXISTS messages(
  id INTEGER PRIMARY KEY,
  body TEXT NOT NULL,
  created TIMESTAMPTZ NOT NULL,
  read BOOLEAN,
  type TEXT NOT NULL,
  title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cached_journey(
  id INTEGER PRIMARY KEY,
  origin TEXT NOT NULL,
  dest TEXT NOT NULL,
  max_hop REAL NOT NULL,
  use_station BOOL NOT NULL DEFAULT false,
  calculated TIMESTAMPTZ NOT NULL,
  UNIQUE (origin, dest, max_hop)
);

CREATE TABLE IF NOT EXISTS cached_journey_steps(
  journey_id INTEGER REFERENCES cached_routes(id),
  src TEXT NOT NULL,
  dest TEXT NOT NULL,
  step SMALLINT NOT NULL,
  dist_src NUMERIC(6,2) NOT NULL,
  dist_dest NUMERIC(6,2) NOT NULL,
  PRIMARY KEY (journey_id, step)
);

CREATE TABLE IF NOT EXISTS json_devices(
  code TEXT PRIMARY KEY,
  fetched_ts TIMESTAMPTZ,
  updated_ts TIMESTAMPTZ,
  location TEXT,
  type TEXT,
  status TEXT,
  data JSONB
);

CREATE TABLE IF NOT EXISTS event_stream(
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  evenid TEXT UNIQUE,
  category TEXT,
  created TIMESTAMPTZ,
  code TEXT,
  event TEXT,
  location TEXT,
  data JSONB
);

CREATE TABLE IF NOT EXISTS device_logs(
  id INTEGER,
  created TIMESTAMPTZ,
  device TEXT,
  type TEXT,
  message TEXT,
  payload JSONB,
  PRIMARY KEY (id, device)
);

CREATE TABLE IF NOT EXISTS tasks(
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  added TIMESTAMPTZ,
  completed TIMESTAMPTZ,
  type TEXT,
  title TEXT,
  details JSONB
);

CREATE TABLE IF NOT EXISTS intent(
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  location TEXT UNIQUE,
  demand JSONB
);

CREATE TABLE IF NOT EXISTS deliveries(
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  origin TEXT,
  destination TEXT,
  ship TEXT UNIQUE,
  cargo JSONB
);

CREATE TABLE IF NOT EXISTS inventory(
  designation TEXT PRIMARY KEY,
  star TEXT REFERENCES stars(designation),
  carbon INT NOT NULL DEFAULT 0,
  conductive INT NOT NULL DEFAULT 0,
  rares INT NOT NULL DEFAULT 0,
  silicates INT NOT NULL DEFAULT 0,
  structural INT NOT NULL DEFAULT 0,
  volatiles INT NOT NULL DEFAULT 0
);
